### ISSUE TITLE
Crash on Casting Skill

### ISSUE THREAD

**Issue by Snayff** [Snayff/notquiteparadise#97]
**Describe the bug**
Casting a skill crashes the game.

**To Reproduce**
1. Press 1 to select skill. 
2. Press a direction to cast.

**Log Output/Stack Trace**
```
2020-09-27 19:18:09,464| DEBUG   | 'players basic attacks projectile' is beginning their turn.
2020-09-27 19:18:09,464| WARNING | 'players basic attacks projectile' tried to use a skill, 'Move', they dont know.
2020-09-27 19:18:09,465| CRITICAL| Something went wrong and killed the game loop!
2020-09-27 19:18:09,467| CRITICAL| Traceback (most recent call last):
2020-09-27 19:18:09,467| CRITICAL|   File "C:/Users/Gabriel/Documents/NotQuiteParadise/scripts/nqp/main.py", line 40, in main    game_loop()
2020-09-27 19:18:09,467| CRITICAL|   File "C:/Users/Gabriel/Documents/NotQuiteParadise/scripts/nqp/main.py", line 88, in game_loop    world.take_turn(turn_holder)
2020-09-27 19:18:09,467| CRITICAL|   File "C:\Users\Gabriel\Documents\NotQuiteParadise\scripts\engine\world.py", line 1059, in take_turn    behaviour.behaviour.act()
2020-09-27 19:18:09,468| CRITICAL|   File "C:\Users\Gabriel\Documents\NotQuiteParadise\scripts\engine\thought.py", line 51, in act    move = world.get_known_skill(entity, "Move")
2020-09-27 19:18:09,468| CRITICAL|   File "C:\Users\Gabriel\Documents\NotQuiteParadise\scripts\engine\world.py", line 667, in get_known_skill    raise Exception("Skill not found")
```

**Comment by Snayff** [comment]
Looks like projectile entity doesnt know move.
```
# thought.py
move = world.get_known_skill(entity, "Move")
skill_instance = move(self.entity, target_tile, self.data.direction)
```
Should be more like
```
#input_processor.py
move = world.get_known_skill(player, "move")
if direction in move.target_directions:
    _process_skill_use(player, move, target_tile, direction)
```
